### ISSUE TITLE
"Issueベースの開発" レビュー依頼

### ISSUE THREAD

**Issue by mk389** [mk389/Giftrail#24]
■Webアプリの概要
このWebアプリは、ユーザー同士でお土産や手土産の情報を簡単に共有できるプラットフォームです。
投稿者がお土産や手土産の写真をアップロードし、5段階評価や詳細なコメントを追加することで、他のユーザーがこれらの投稿を参考にして、お土産や手土産を選ぶ際の判断材料とすることができます。
また、検索機能で目的の投稿をスムーズに見つけることが可能です。
お土産の選び方を楽しく、便利にするアプリです。

■1週間辺りの開発に向けられる時間
- 1週間あたり：14時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
https://github.com/users/mk389/projects/1

■MVPリリースまで
- [ ] rails new
- [ ] render.comにデプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ナビゲーションメニュー
- [ ] Amazon S3設定
- [ ] ログイン機能
- [ ] パスワードリセット機能
- [ ] 投稿一覧
- [ ] プロフィール編集
- [ ] 投稿作成機能
- [ ] 投稿削除機能
- [ ] 評価機能
- [ ] 投稿詳細
- [ ] 検索フォーム
- [ ] タグ一覧機能
- [ ] 検索結果
- [ ] ソーシャルシェア機能

■MVP後
- [ ] GoogleMap
- [ ] お問い合わせ
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] お気に入り機能
- [ ] コメント機能

■MVPレビュー依頼予定日
予定日：2024年 12月 16日

**Comment by ippei-shimizu** [comment]
issueのタイトルに番号を使用しているものがいくつかありました。（ユーザー登録(1), ユーザー登録(2)など）
このタイトルでは、具体的になにをやるのかがわかりずらいため、番号ではなく具体的はタイトルに変更して、再提出をお願いします。

**Comment by mk389** [comment]
ご確認いただきありがとうございます。
修正してみましたので、再度ご確認のほどよろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- ソーシャルシェア
- 星評価
- パスワードリセット
- Googleログイン
- プロフィール編集
